### ISSUE TITLE
Wallet: gibberish select option for type of wallet

### ISSUE THREAD

**Issue by fajarvm** [nemfoundation/symbol-desktop-wallet#103]
Wallets > My Wallets > Add or import a wallet. The pop up window "Configure your new wallet" has a "Select The Type Of Wallet:" selection with one selectable option being "please_select". This, I believe, is unintended.

<img width="1031" alt="Screenshot 2020-03-17 at 11 43 22" src="https://user-images.githubusercontent.com/3041538/76849263-5bc6aa80-6845-11ea-98ae-5df460f7952b.png">

**Comment by decentraliser** [comment]
thanks for reporting!
