### ISSUE TITLE
Wallet creation flow should drop "Sign Up" terminology

### ISSUE THREAD

**Issue by evias** [nemfoundation/symbol-desktop-wallet#108]
Drop **sign up terminology** in favor of **new wallet**, **create new wallet**, **import wallet**.

> For new wallet creation - Change terms to "Create New Wallet" and "Import Wallet" and remove "Sign Up" terminology

**Comment by meyns** [comment]
I would suggest add an import wallet method using the private key instead of the mnemonic phrase

**Comment by vincent-lee90** [comment]
Maybe using the private key or using the mnemonic phrase can exist at the same time

**Comment by David0817** [comment]
@evias  this issue has been completed and PR has merged, but it's not related to PR
