### ISSUE TITLE
Wallet doesn't show transactions from symbol-cli

### ISSUE THREAD

**Issue by meyns** [nemfoundation/symbol-desktop-wallet#109]
My wallet does not show transactions made with symbol-cli.
It does show normal transactions made in the wallet.
If in dashboard on the bottom if I scroll through the pages I can see on page 5 older normal transactions using the wallet.

**Comment by meyns** [comment]
![image](https://user-images.githubusercontent.com/6676974/76881845-09ec4780-687a-11ea-9437-65861e9a1a58.png)
This my account

**Comment by decentraliser** [comment]
hi! can you please paste the mnemonic or send it to me as a dm?

**Comment by decentraliser** [comment]
This is quite odd, you must be on a different network

Note that symbol-cli is not compatible with the hd-wallets (mnemonics), could you please send me the private key here or in a DM?

**Comment by meyns** [comment]
DEE90FB1A813BB3E5CF00CC2EF8CD7DF0D0E5CA1BFD1C43907E53A73B8B7CA0D
transactions are viewable on the explorer

**Comment by decentraliser** [comment]
![image](https://user-images.githubusercontent.com/36499647/76886264-80f60000-68bb-11ea-8300-e40a1541a74d.png)

here is what I have with this key

Can you please send me the node you are using with the CLI?

**Comment by meyns** [comment]
Node is 188.166.75.241
In your screenshot you see the last transaction I made in the wallet, but all other transactions are hidden made with symbol-cli.
(btw same this happened last time in the explorer. The transactions from symbol-cli gave a no data found or something
I think this issue is the same issue in the explorer: https://github.com/nemfoundation/nem2-explorer/pull/318

**Comment by decentraliser** [comment]
sounds like you are right!
Nice catch! Thanks
