### ISSUE TITLE
Cannot make multisig account

### ISSUE THREAD

**Issue by meyns** [nemfoundation/symbol-desktop-wallet#110]
Trying to create a mulsitig account fails.
Sending the first transaction goes fine, and I am able to confirm the cosignatures in the cosig accounts. But after confirming the cosignatures nothing happens, there is no multisig created.
If the cosignatures are not confirmed no transactions can be done from the master account, but after the cosignatures have accepted being cosigs, I can send like normal from the master account.

**Comment by meyns** [comment]
![image](https://user-images.githubusercontent.com/6676974/76882312-c47c4a00-687a-11ea-88e6-b80fbdfcc8fe.png)
Ps: this is the same account as issue #109

**Comment by decentraliser** [comment]
"but after the cosignatures have accepted being cosigs, I can send like normal from the master account." 

This sounds like normal behaviour, could you explain what you did point by point until the problem you met?

Thanks!

**Comment by meyns** [comment]
1- convert master account to multisig (3 public keys, 2 for approval, 3 for removal)
2- Go to partial transactions on all cosigs and sign transaction
2b- if transactions are not signed then no transactions can be made from master (normal behaviour)
3- After all cosigs have signed situation is as before. No multisig is created (I can send like normal again)

**Comment by decentraliser** [comment]
I just tried and I have no problem on my side

At step 3, if you login and logout, are you still able to start a multisig conversion from master account?

This behaviour should have been fixed in the latest release, v0.9.6-beta1

**Comment by meyns** [comment]
Tried it again, but same result. Also after relogin same scenario. I have a funds lock transaction in the master account.
In the multisig tab it still says "This account does not have co-signatories."

**Comment by meyns** [comment]
Running Symbol Wallet v0.9.6-beta1

**Comment by decentraliser** [comment]
This is likely to be an issue with the refresh events occuring when transactions are validated
