### ISSUE TITLE
Styles issue. Some items are not aligned properly

### ISSUE THREAD

**Issue by OlegMakarenko** [nemfoundation/symbol-desktop-wallet#111]
![image](https://user-images.githubusercontent.com/33131259/76899859-fdc7b080-68a0-11ea-9e95-a8fba9ba50c9.png)

Text should be centered:
![image](https://user-images.githubusercontent.com/33131259/76900196-8d6d5f00-68a1-11ea-8473-03f210754eee.png)

**Comment by NemTechCN** [comment]
[](https://github.com/nemfoundation/symbol-desktop-wallet/pull/123)

**Comment by NemTechCN** [comment]
it's fixed and merged in master
