### ISSUE TITLE
Feat: Extend a mosaic duration

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/symbol-desktop-wallet#125]

**Comment by vincent-lee90** [comment]
Hi , decentraliser
I want to know more details  about this issue if you would like to do.
Thanks.

**Comment by decentraliser** [comment]
Basically it is the same as extending namespaces duration, but for mosaics

Le ven. 10 avr. 2020 à 11:28, vincent-lee90 <notifications@github.com> a
écrit :

**Comment by vincent-lee90** [comment]
https://nemtech.github.io/concepts/mosaic.html#duration

**Comment by vincent-lee90** [comment]
Different from namespaces, a mosaic duration cannot be extended after its creation

**Comment by decentraliser** [comment]
Closed as it is not possible as per the docs, thanks
