### ISSUE TITLE
the layout for "creating new namespace" page

### ISSUE THREAD

**Issue by David0817** [nemfoundation/symbol-desktop-wallet#126]
1.Fill the page with forms,It seems to have too many layers
2. Change the description to an icon and click display
![image](https://user-images.githubusercontent.com/18167466/77046069-44cab880-69fd-11ea-9e98-dda99192f75f.png)

**Comment by Kyrylog** [comment]
Should be XYM, not XEM 
![image](https://user-images.githubusercontent.com/33864106/77201304-ef71d280-6af4-11ea-936d-cab30a2f912c.png)

**Comment by evias** [comment]
fixed with 28e1ac6c
