### ISSUE TITLE
generateMnemonic broken when working on an incomplete account.

### ISSUE THREAD

**Issue by fboucquez** [nemfoundation/symbol-desktop-wallet#128]
Hi guys, I'm new to the wallet. Please forgive me If the terminology I'm using is not right. 

I have created an incomplete account (the server was down), where the mnemonic wasn't generated properly.  When I try to logging, the login screen takes me to the /generateMnemonic wizard step/page. Once I finish generating the entropy, the wizard step fails with a `Something went wrong when generating your wallet seed.`

It seems like the `currentPassword: 'temporary/password'` is undefined when jumping from the login page to the wizard. Should login page save the password in the store?

![image](https://user-images.githubusercontent.com/5390558/77079347-a62b6100-69d6-11ea-9598-6f53bbedf436.png)

The logs: 
(I added a `console.log` [here](https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/src/views/pages/accounts/create-account/generate-mnemonic/GenerateMnemonicTs.ts#L127))

````
An error happened while generating Mnenomic: TypeError: Cannot read property 'value' of null
    at Function.encrypt (AESEncryptionService.ts?d75d:58)
    at GenerateMnemonic._callee$ (GenerateMnemonicTs.ts?35e7:109)
    at tryCatch (runtime.js?98b8:45)
    at Generator.invoke [as _invoke] (runtime.js?98b8:271)
    at Generator.prototype.<computed> [as next] (runtime.js?98b8:97)
    at eval (tslib.es6.js?9ab4:74)
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js?9ab4:70)
    at GenerateMnemonic.saveMnemonicAndGoToNextPage (GenerateMnemonicTs.ts?35e7:34)
    at GenerateMnemonic.handleMousemove (GenerateMnemonicTs.ts?35e7:95)
````

**Comment by decentraliser** [comment]
yes, this is a recent regression! Will fix it, thanks for reporting!

**Comment by decentraliser** [comment]
is there a fix to that in an open PR @NemTechCN ?

**Comment by fboucquez** [comment]
I got a quick fix. I can push a PR, this PR could be superseded if you are refactoring the whole process. Should I create a PR?

**Comment by NemTechCN** [comment]
> is there a fix to that in an open PR @NemTechCN ?

no,that open pr for importMnemonic

**Comment by decentraliser** [comment]
When I talked about "a recent regression" I was thinking about another bug, so, nice catch!
