### ISSUE TITLE
Registering a new wallet should have form validation about character symbols

### ISSUE THREAD

**Issue by David0817** [nemfoundation/symbol-desktop-wallet#134]
This seems like a strange name
like this:
<img width="991" alt="Form validation" src="https://user-images.githubusercontent.com/18167466/77132706-4b0f7200-6a9b-11ea-80b6-d875987d2bf3.png">

**Comment by evias** [comment]
"seems" xD

Thanks for the finding :+1:

**Comment by decentraliser** [comment]
@evias this is true for all plain text fields, such as wallet names

Can you give a guideline on what chars to avoid? Is there a security issue here?

**Comment by evias** [comment]
@decentraliser @David0817 please revive this and make sure any **input** fields use a sanitizer to remove scripts/tags ("strip tags logic")
