### ISSUE TITLE
Harcoded network config properties can be loaded from rest

### ISSUE THREAD

**Issue by fboucquez** [nemfoundation/symbol-desktop-wallet#140]
Network configuration can be now be loaded from rest. The hardcoded values in the [network.conf.json ](https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/config/network.conf.json#L26) could be removed

The wallet should store the values from [rest getNetworkProperties](https://nemtech.github.io/symbol-openapi/#operation/getNetworkProperties) and keep store them in the database for offline resilience. The UI components should load the values from memory through getter/service and not from the file like [here](https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/src/components/ApprovalAndRemovalInput/ApprovalAndRemovalInputTs.ts#L32)

Related (Same EPIC):
https://github.com/nemfoundation/symbol-desktop-wallet/issues/139
https://github.com/nemfoundation/symbol-desktop-wallet/issues/50
https://github.com/nemfoundation/symbol-desktop-wallet/issues/33

**Comment by fboucquez** [comment]
In my https://github.com/nemfoundation/symbol-desktop-wallet/pull/177 PR, The NetworkService will load and cache the NetworkModel that UI components (via getter/store) will be able to refer when using the properties

https://github.com/NEMStudios/symbol-desktop-wallet/blob/storage-refactoring/src/services/NetworkService.ts#L72

https://github.com/NEMStudios/symbol-desktop-wallet/blob/storage-refactoring/src/core/database/entities/NetworkModel.ts#L33

**Comment by evias** [comment]
fixed with merge of #177
