### ISSUE TITLE
An error occurred at the position of the ADD ICON

### ISSUE THREAD

**Issue by David0817** [nemfoundation/symbol-desktop-wallet#141]
The position of the ADD ICON changed when I added the wallet address
<img width="1172" alt="The location of the ADD ICON changed when I added the wallet address" src="https://user-images.githubusercontent.com/18167466/77295797-858a4080-6d21-11ea-9cad-de8b6a612569.png">

**Comment by evias** [comment]
merged with 28e1ac6c
