### ISSUE TITLE
When the table list is empty, the tips should be grayed 

### ISSUE THREAD

**Issue by David0817** [nemfoundation/symbol-desktop-wallet#149]
1.include module (transcation list/mosaic list/ namespace list)
2.remove background-color

<img width="480" alt="tips should be grayed" src="https://user-images.githubusercontent.com/18167466/77505277-ae374500-6e9d-11ea-90ba-08cf89ebf46f.png">

**Comment by evias** [comment]
merged with 28e1ac6c
