### ISSUE TITLE
upgrade planned?

### ISSUE THREAD

**Issue by roccomuso** [nemfoundation/symbol-desktop-wallet#158]
Is there an upgrade planned? https://forum.nem.io/t/migration-committee-community-update-13/24606

Is there a mainnet upgrade planned? 
Do client API or crypto lib change?

Any JS SDK branch I can keep track of?

**Comment by decentraliser** [comment]
Hi @roccomuso !
- Is there an upgrade planned?
=> You can follow all the development activity on the 2 repos of the foundation: github.com/nemfoundation ; github.com/nemtech

- Is there a mainnet upgrade planned?
=> News about the mainnet shall be communicated by the migration committee

- Any JS SDK branch I can keep track of?
=> The JS SDK team commits to the master branch

For technical questions, please join the slack, at nem2.slack.com
