### ISSUE TITLE
 Form and text alignment

### ISSUE THREAD

**Issue by David0817** [nemfoundation/symbol-desktop-wallet#162]
1.the login page placeholder color light
2, the wallet information page to edit the name icon and view the private key icon size adjustment, remain the same
3.wallet backup, harvesting two page icon size and left and upper and lower space adjustment, keep the same
4.wallet information, wallet backup, harvesting three pages of content, the first line of text and border spacing adjustment, keep consistent
5.top navigation toggle node dot and icon space adjustment, and the Console icon before the center

**Comment by evias** [comment]
merged with 28e1ac6c
