### ISSUE TITLE
UInt64.compact() may return an number[] (not an number) when overflow

### ISSUE THREAD

**Issue by fboucquez** [nemfoundation/symbol-desktop-wallet#163]
The wallet is currently using `UInt64.compact()` to perform numeric operations of UInt64. This method may return an array of numbers instead of a number breaking the process. 

````
    it('should compact UInt64 number', () => {
        const notOverflowed = UInt64.fromNumericString('44444')
        expect(notOverflowed.toString()).to.be.equal('44444');
        expect(notOverflowed.compact()).to.be.equal(44444);

        const overflowed = UInt64.fromNumericString('18446744073709551614')
        expect(overflowed.toString()).to.be.equal('18446744073709551614');
        //NOT A NUMBER
        expect(overflowed.compact()).to.be.equal([ 4294967294, 4294967295 ]); 
    });
````

This problem could be bigger,  `UInt64` numbers may overflow when converting to standard `number`.

The SDK team is analyzing the pros and cons of replacing UInt64 for native BigInt.  I'm reporting this issue but I would wait for the SDK decision on the UInt64 format.

**Comment by decentraliser** [comment]
note that there is another bug relative to UInt64, with an unwanted? behaviour from this big number:

max number
9007199254740991
9_007_199_254_740_991

![image](https://user-images.githubusercontent.com/36499647/77708916-6f6fcf00-7004-11ea-9fa4-d22ef3a10240.png)

**Comment by fboucquez** [comment]
We are keen to migrate UInt64 to bigint in the SDK. Please park this issue until we get a better way of representing uint64

**Comment by decentraliser** [comment]
I close this issue, we will open a new one for SDK upgrade
