### ISSUE TITLE
wallet list is unable to load in the 'wallets/details'

### ISSUE THREAD

**Issue by vincent-lee90** [nemfoundation/symbol-desktop-wallet#165]
![image](https://user-images.githubusercontent.com/10797419/77714304-a4cfe900-7013-11ea-9e22-f0a29ffb5f26.png)
![image](https://user-images.githubusercontent.com/10797419/77714347-c4ffa800-7013-11ea-8727-3aafc51bab96.png)

the result is shown in the first picture.
the problem is that 
`const netBalance = currentInfo.mosaics.find(m => m.id.equals(this.networkMosaic))`
**if result of Array method find will be undefined when there is no match element in the Array**
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find]

so
![image](https://user-images.githubusercontent.com/10797419/77714835-ff1d7980-7014-11ea-9e56-bed9e53103be.png)

**Comment by vincent-lee90** [comment]
![image](https://user-images.githubusercontent.com/10797419/77714905-2b38fa80-7015-11ea-9b3c-fc5c095afe60.png)

**Comment by evias** [comment]
fixed with 87e58b25
