### ISSUE TITLE
Incorrect use of namespaceGracePeriodDuration

### ISSUE THREAD

**Issue by fboucquez** [nemfoundation/symbol-desktop-wallet#173]
Hi team, I think there are 2 issues calculating the namespace expiration status:

1) the namespaceGracePeriodDuration loaded from the static configuration file is incorrect.

https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/src/services/AssetTableService/NamespaceTableService.ts#L111

https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/src/views/forms/FormExtendNamespaceDurationTransaction/FormExtendNamespaceDurationTransactionTs.ts#L137

It should be 

`const {namespaceGracePeriodDuration} = networkConfig.networks['testnet-publicTest'].properties`

Although this issue will be superseded by https://github.com/nemfoundation/symbol-desktop-wallet/issues/140 eventually.  (I'm working on it now)

2) The tested /hardocded namespaceGracePeriodDuration value is 172800 (seconds? blocks?)
https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/config/network.conf.json#L38

But the configured one is '30d' = 2592000 seconds (much higher than 172800)

It seems the wallet is using namespaceGracePeriodDuration in terms of blocks, but the configuration seems to be talking in days. Is the network configuration incorrect? @dgarcia360 @evias @decentraliser

**Comment by decentraliser** [comment]
It is in blocks

**Comment by fboucquez** [comment]
The wallet should start using the value in seconds in order to be compatible with the rest network configuration. 

https://nemtech.github.io/concepts/namespace.html#duration

I'm working on a fix for this issue. I'll send a PR.

**Comment by dgarcia360** [comment]
``namespaceGracePeriodDuration`` configuration is correct and it is in days.

**Comment by decentraliser** [comment]
30*24*60*60/targetBlockTime is the formula, with 15sec as targetBlockTime.
This constant is needed in blocks in the app

**Comment by decentraliser** [comment]
@fboucquez did you have another look according to the formula I pasted above?

The way it is done in the wallet looks good to me

**Comment by fboucquez** [comment]
Hi @decentraliser 

The value returned via rest is in duration = 30d  = 2592000 seconds.
What I have done in my PR is converting namespaceGracePeriodDuration to duration (2592000) so they mean the same in both places. Then use the  `/ targetBlockTime` formula (converting it back to 172800). 

https://github.com/NEMStudios/symbol-desktop-wallet/blob/storage-refactoring/src/services/NamespaceService.ts#L72

After fixing issue 1 before your release, you can change the namespaceGracePeriodDuration value to 2592000 and change how it's used (for consistency). Or, if you think my branch can be merged in the future after release, leave it, the PR will fix it eventually. 

My PR loads and caches the properties from rest and it fixes the namespaceGracePeriodDuration "type". It also centralizes how namespace expiration is calculated (the logic is duplicated in master).
