### ISSUE TITLE
Issue: Cannot read property 'reset' of undefined"

### ISSUE THREAD

**Issue by fboucquez** [nemfoundation/symbol-desktop-wallet#175]
After doing some operations like unlink an alias, the following stacktrace is shown:

![image](https://user-images.githubusercontent.com/5390558/77974831-aa0c8c80-72ce-11ea-8b99-01586d7c3d14.png)

vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'reset' of undefined
    at FormAliasTransaction.eval (FormTransactionBase.ts?eb0f:413)
    at Array.eval (vue.runtime.esm.js?2b0e:1980)
    at flushCallbacks (vue.runtime.esm.js?2b0e:1906)

**Comment by decentraliser** [comment]
This comes from the form validation reset method after form submission

I think that it is called after the modals are destroyed

https://github.com/nemfoundation/symbol-desktop-wallet/blob/684bf5c191cf6e8f518fc1d849455de5aed60157/src/views/forms/FormTransactionBase/FormTransactionBase.ts#L411

**Comment by vincent-lee90** [comment]
the reason cause the error is callback function what is in `this.$nextTick`
when the callback in **nextTick** is called and the component which is related to $ref  had been destroyed,that's what happened.
So,I have 2 solutions.
1.use callback in  beforeDestroy
2.put callback in the last step.
I want to know  whether if  there is  any better idea?

**Comment by vincent-lee90** [comment]
I removed the $nextTick here,because its very hard to know when the model has been updated

**Comment by decentraliser** [comment]
In what PR did you try it?

I would like to make sure that the form reset behaves as expected without
the nextTick

Le lun. 13 avr. 2020 à 11:14, vincent-lee90 <notifications@github.com> a
écrit :
