### ISSUE TITLE
enhance:adjust the style of invoice and  transfer

### ISSUE THREAD

**Issue by vincent-lee90** [nemfoundation/symbol-desktop-wallet#179]
1.add the default QR code in the invoice.
2.align the styles in invoice
3.adjust the style of invoice input and the transfer input
4.mosaic delete button will be seen when it is the last one and the items's length is over 1
5.strengthen the code in order to decrease the error in the console
style before:
![image](https://user-images.githubusercontent.com/10797419/78005274-e9d68100-736d-11ea-8860-570215eb62d7.png)
![image](https://user-images.githubusercontent.com/10797419/78005310-f65ad980-736d-11ea-95ef-4d7415570d38.png)
style after:
![image](https://user-images.githubusercontent.com/10797419/78005388-138fa800-736e-11ea-8058-5972c40b234f.png)
![image](https://user-images.githubusercontent.com/10797419/78005421-1ee2d380-736e-11ea-94e2-443b4bc6b240.png)

**Comment by evias** [comment]
fixed with 1bf66f01
