### ISSUE TITLE
add refresh button and show/hide expired button on namespace page

### ISSUE THREAD

**Issue by vincent-lee90** [nemfoundation/symbol-desktop-wallet#186]
before:
![image](https://user-images.githubusercontent.com/10797419/78224694-8c703a80-74fb-11ea-90d8-3d90e10ed202.png)

after:
![image](https://user-images.githubusercontent.com/10797419/78224380-0ce26b80-74fb-11ea-986e-1cc6ea031ff5.png)

**Comment by evias** [comment]
fixed with 32adc15c
