### ISSUE TITLE
Incorrect max fee on transaction confirmation view.

### ISSUE THREAD

**Issue by cryptoBeliever** [nemfoundation/symbol-desktop-wallet#188]
Max fee on transaction confirmation pop-up is presented in incorrect why. 
On the example below, it's 50 000 XYM but should be 0.05 XYM.

Wallet version: v 0.9.6
Screenshots attached. 

![2](https://user-images.githubusercontent.com/17684281/78237765-0c86a800-74dc-11ea-9501-c478163c53ca.png)

![1](https://user-images.githubusercontent.com/17684281/78237743-055f9a00-74dc-11ea-9b7f-1a30cef5d8e6.png)

**Comment by cryptoBeliever** [comment]
Same problem on other transaction confirmations (for example mosaic and namespace)

**Comment by cryptoBeliever** [comment]
@decentraliser same thing with "Paid Fee" for confirmed transactions. Should I create separate issue for that?

**Comment by decentraliser** [comment]
no it's fine, I fix both in the same PR
Thanks!
