### ISSUE TITLE
Hide unimplemented features

### ISSUE THREAD

**Issue by cryptoBeliever** [nemfoundation/symbol-desktop-wallet#194]
When I click Download keys from "Wallet backup" view there is no reaction at all.

![wallet_backup](https://user-images.githubusercontent.com/17684281/78257408-161f0880-74fa-11ea-900b-d81183fd3d43.png)

**Comment by cryptoBeliever** [comment]
Same problem with:
- Harvesting -> Setup a remote account
- Harvesting -> Send delegation request(s)

Browser: Chrome  80.0.3987.87
Wallet: v 0.9.6

**Comment by decentraliser** [comment]
Harvesting is not ready yet
I open a thread in the slack
