### ISSUE TITLE
Password change related bugfixes

### ISSUE THREAD

**Issue by cryptoBeliever** [nemfoundation/symbol-desktop-wallet#195]
- [ ] An profile's wallet array *sometimes* get emptied when the password is updated
- [x] Wallets password (SimpleWallet) do not get updated when a profile password is updated
- [x] When having a profile A and B, and changing password for B, B's new password is needed to login with A

**Comment by decentraliser** [comment]
@cryptoBeliever I tried to break it in all possible ways, on web and exe build, it looks fine to me

Could you please try again and confirm that it is really broken on your end?

**Comment by decentraliser** [comment]
I have a situation where

I have profile A and B, with the same password: password

I change profile B's password to newPassword

I now have to use newPassword to login with A
I have to use password to send a transaction with A

I will assume this is the cause of your problem for now

**Comment by decentraliser** [comment]
Sometimes the wallets array gets emptied in the profile table...

**Comment by cryptoBeliever** [comment]
@decentraliser 

I'm able to reproduce this in incognito to remove all wallets.
1. Open wallet in incognito mode (web version.
2. Create account aaa with password gggggg123
3. Logout (this seems to be important part)
4. Login
5. Change password to hhhhhh123
6. Logout
7. I'm not able to login using new or old password.
