### ISSUE TITLE
Multisig account starts with "A"

### ISSUE THREAD

**Issue by dgarcia360** [nemfoundation/symbol-desktop-wallet#205]
The wallet shows an account starting with "A", but accounts on test net should start with "T".

**Steps to reproduce the issue:**
1. Created a multisig account with the wallet.
2. Logged with the cosignatory account.
3. Tried to issue a transaction involving the multisig, the account appeared like in the photo below.

![image](https://user-images.githubusercontent.com/9107969/78347545-9005cf00-7598-11ea-8dde-d3d8158361fa.png)

NOTE: The address looks right when login into the wallet.

![image](https://user-images.githubusercontent.com/9107969/78347578-9dbb5480-7598-11ea-8d14-78a4f8d1e98c.png)

**Comment by evias** [comment]
its missing the first character in signer selector.
