### ISSUE TITLE
Multiple mosaics cannot be bound to the same namespace at the same time

### ISSUE THREAD

**Issue by David0817** [nemfoundation/symbol-desktop-wallet#228]
With the same namespace, each time extend the rental, the new  mosaic can be bound it again .
As shown below:

![image](https://user-images.githubusercontent.com/18167466/79085484-4e7cdd00-7d6b-11ea-95c7-c2cc41830a53.png)

**Comment by decentraliser** [comment]
Can you please paste your address here?

**Comment by David0817** [comment]
TC67WV76F7YGD3M5WRX7EPGGXBWTVWE63362UZ4X

**Comment by David0817** [comment]
I use a new  profile test:
![image](https://user-images.githubusercontent.com/18167466/79090942-f6030b00-7d7d-11ea-8f9a-2d7b74295f74.png)

**Comment by decentraliser** [comment]
looks like a REST or server issue
@evias do you know about that?
http://explorer.symboldev.network/account/TC67WV76F7YGD3M5WRX7EPGGXBWTVWE63362UZ4X

**Comment by decentraliser** [comment]
![image](https://user-images.githubusercontent.com/36499647/79091757-2009fc80-7d81-11ea-98b7-2856c0c70cb8.png)

**Comment by decentraliser** [comment]
closed in favour of
https://github.com/nemtech/catapult-server/issues/65
https://github.com/nemtech/catapult-server/issues/66
