### ISSUE TITLE
cryptoJS latest introduces breaking change with iv type

### ISSUE THREAD

**Issue by vincent-lee90** [nemfoundation/symbol-desktop-wallet#235]
The package 'crypto-js' has updated a file 13 days ago
![image](https://user-images.githubusercontent.com/10797419/79118560-d9d48d80-7dc0-11ea-8690-70aba5be4dd5.png)
![image](https://user-images.githubusercontent.com/10797419/79118745-48195000-7dc1-11ea-86e1-9b94c2c986c7.png)
[https://github.com/DefinitelyTyped/DefinitelyTyped/commit/1cc65a1bdee4e5079e3c77e6ad28e6ee2c0411c9]
it will cause some errors when we reinstall the `node modules`,as the follow:
![image](https://user-images.githubusercontent.com/10797419/79118841-84e54700-7dc1-11ea-8d14-993436af9f11.png)

**Comment by decentraliser** [comment]
will be fixed by #277
