### ISSUE TITLE
REST queries triggered by a change of active wallet should be debounced

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/symbol-desktop-wallet#239]
If you switch wallets quickly (but not crazy quick, like 1 / 500ms) in the wallet sections, it will cause a too many request error

@fboucquez that's something I observed in #177, but that is true with current as well

**Comment by evias** [comment]
is this still active @decentraliser ?

**Comment by decentraliser** [comment]
My understanding is that it will be worked on in the SDK side, if yes then
we can close
