### ISSUE TITLE
Bug in wallet import process

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/symbol-desktop-wallet#240]
**In import**
1. Import a mnemonic
2. Go to next step
3. Go back to the mnemonic import view
4. Click "Return to password settings"
=> Nothing happens, an error is thrown
vue.esm.js:1897 TypeError: Cannot read property 'getIdentifier' of null
    at e.value (ImportMnemonicTs.ts:86)
    at nt (vue.esm.js:1863)
    at HTMLButtonElement.r (vue.esm.js:2188)
    at HTMLButtonElement.Fo.o._wrapper (vue.esm.js:7565)

**In create**
Once you have passed the step when you have to move your mouse, there is no way to cancel the new account creation process

**Comment by evias** [comment]
fixed in 0.9.9
