### ISSUE TITLE
Custom mosaic decimal validation.

### ISSUE THREAD

**Issue by fboucquez** [nemfoundation/symbol-desktop-wallet#245]
Hi team, 

Currently, the decimal validation in relative amount input uses the network/global/currency configuration (6 decimals). If you have custom mosaics with smaller divisibility, the validator would still use the 6 divisibility and the result is that the user doesn't know the smaller fractions could be ignored.

My custom mosaic has divisibility of 3:

![image](https://user-images.githubusercontent.com/5390558/79468801-c51d1300-7fd5-11ea-990c-261615ac337f.png)

Validation should say _must have 3 decimal or less_ 

and if I reduce the number to 6, the last 3 decimals are ignored

![image](https://user-images.githubusercontent.com/5390558/79468960-fdbcec80-7fd5-11ea-85f9-530dd13d4a97.png)

The validator should be configurable with the mosaic divisibility, so it's clear how many decimals are used to avoid ignored decimals. Note that if the mosaic's divisibility is 0, only integer should be accepted.

**Comment by decentraliser** [comment]
We had that in the previous v, I didn't implement it when redoing the form
for speed purposes


This is needed but it might be touchy to implement well

**Comment by fboucquez** [comment]
We may be able to implement it in my new PR. Known mosaic infos are prefetched so it doesn't cost I/O

**Comment by decentraliser** [comment]
It's better to keep it separate, dynamic field validation can cause some
reactivity issues

**Comment by evias** [comment]
status of this after PR#177 merge @fboucquez ?

**Comment by fboucquez** [comment]
Nop, this is still an issue after the merge. 

While doing the validation, we could upgrade the 2 validators that are still using the hardcoded config file. I haven't got time to fix it. 

https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/src/core/validation/CustomValidationRules.ts#L20

https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/src/core/validation/ValidationRuleset.ts#L64

I think to fix this one, the maxMosaicDivisibility should be the divisibility of the mosaic to be validated, not the network or the static config file maxMosaicDivisibility.
