### ISSUE TITLE
Block lazy loading

### ISSUE THREAD

**Issue by fboucquez** [nemfoundation/symbol-desktop-wallet#246]
At the moment, _all_ blocks of known transactions are loaded and cached when booting or loading new confirmed transactions. This has a few problems

1) Keeping a cache of all the blocks could take too much memory and it could be a memory leak as it grows. 
2) It has a custom throttling mechanism that we try to avoid if possible. Wallet needs many remote calls (maybe "too many")
3) It's only used to show Paid Fee (effective fees) on the shown transactions.
4) The team is discussing to not shown the Paid Fee in the Amount column of the dashboard

![image](https://user-images.githubusercontent.com/5390558/79469770-fcd88a80-7fd6-11ea-94b8-fa99e5c472c1.png)

and to show the Paid Fee only in the Transaction Description Popup

![image](https://user-images.githubusercontent.com/5390558/79469836-1083f100-7fd7-11ea-93ca-bd1ab9309a1c.png)

If the wallet only shows the Paid Fee in the popup, we can just load the block for that given transaction (or a range to reuse the call/prefretch) one the popup is open (lazily). This could be a custom TransactionPaidFeeAmount that caches the value for a time.

I'm happy to implement this once my PR is merged (it's getting close to be merged)

https://github.com/nemfoundation/symbol-desktop-wallet/pull/177

@evias @decentraliser

**Comment by decentraliser** [comment]
I think that fetching all the blocks while not using a global fetching service that would put these fetch in the lowest priority is an issue and that it might be (on of the main) responsible for "too many requests issues". 

Storing all the blocks when you have many wallets that have many transactions could eventually bring a memory problem, although I'm not sure whether it would really be significant as we are doing a fully-featured desktop app.

I think that storing an object like {txHash: actualFee} would be a good tradeoff

To a broader extent, I've seen many tax and accounting related concerns in other blockchain projects communities, where people need a breakdown of their transactions, with a clear identification of transaction fees.

If we have an object such as the one described above, we could easily allow CSV dumps in the future, that wallet user might find very useful.

I think that overall, people care about how much they spend in tx fees

**Comment by evias** [comment]
ACK to remove Fee column in listing and imlement lazy loading

**Comment by fboucquez** [comment]
We still need this in order to show the paid fee in the transaction popups. That's allows wallet to load blocks on demand

**Comment by evias** [comment]
merged in master
