### ISSUE TITLE
Multi-Signature accounts page implementation

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/symbol-desktop-wallet#247]
Components:

src/views/multisig
Task description:
This component should provide with multiple tabs to work with Multi-Signature accounts. This includes the current wallet's multi-signature graph and graphs of accounts of which the current wallet is a cosignatory.

Store getters wallet/currentWallet can be used and store action wallet/REST_FETCH_MULTISIG can be dispatched at component creation to permit having an updated blockchain state of the current wallet.

Forms for the convertion of accounts and the modification of previously created multi-signature accounts will also be presented in subsequent tabs.

Actionable Items:

- [ ]  MultisigAccountGraphDisplay
- [x]  Integrate FormMultisigAccountModificationTransaction
- [ ]  CosignatoriesRequestList extends TransactionList
- [x]  TransactionFormBase SignerSelector should dispatch "wallet/initialize" for selected
  - [x]  AccountBalancePanel should emphasize "different signer" mode when signer changes

**Comment by evias** [comment]
multi-signature flow to be redefined with UI rework, closing this issue as MVP stands for multisig.
