### ISSUE TITLE
Mnemonic input: Words should show in pretty boxes

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/symbol-desktop-wallet#25]
Words should show in the same spans as the ones used for mnemonic verification

![image](https://user-images.githubusercontent.com/36499647/75839015-9fabbf80-5e02-11ea-9c68-0ac5c48dc767.png)

**Comment by NemTechCN** [comment]
https://github.com/nemfoundation/symbol-desktop-wallet/pull/95 @decentraliser @evias
