### ISSUE TITLE
Invalid 'isCosignatoryMode' when changing transaction status selector

### ISSUE THREAD

**Issue by fboucquez** [nemfoundation/symbol-desktop-wallet#251]
Go to the transcation list, select a multisign account.

"There should be a "The selected transaction signer is a multi-signature account." is shown correctly,

Then change the Transaction Status to something else like 'confirmed'

The banner is gone when the signer is still multisig

The problem is the incorrect state change with` this.$store.commit('wallet/isCosignatoryMode',false)`

I'm fixing it in the PR

https://github.com/nemfoundation/symbol-desktop-wallet/pull/177

**Comment by evias** [comment]
merged with #177
