### ISSUE TITLE
Error in log when clicking the current menu on the left menu

### ISSUE THREAD

**Issue by fboucquez** [nemfoundation/symbol-desktop-wallet#252]
vue-router.esm.js?8c4f:2089 Uncaught (in promise) NavigationDuplicated {_name: "NavigationDuplicated", name: "NavigationDuplicated", message: "Navigating to current location ("/wallets/details") is not allowed", stack: "Error↵    at new NavigationDuplicated (webpack-int…node_modules/vue/dist/vue.runtime.esm.js:2178:14)"}

**Comment by decentraliser** [comment]
This does not look fixed to me, I still get it when landing on Home after creating a new account

vue.esm.js?a026:628 [Vue warn]: Error in v-on handler (Promise/async): "NavigationDuplicated: Navigating to current location ("/home") is not allowed"

found in

---> <FinalizeTs> at src/views/pages/profiles/create-profile/finalize/Finalize.vue
       <CreateProfileTs> at src/views/pages/profiles/create-profile/CreateProfile.vue
         <RouterPage> at src/views/layout/RouterPage.vue
           <PageLayoutTs> at src/views/layout/PageLayout/PageLayout.vue
             <AppTs> at src/app/App.vue
               <Root>
warn @ vue.esm.js?a026:628
logError @ vue.esm.js?a026:1893
globalHandleError @ vue.esm.js?a026:1888
handleError @ vue.esm.js?a026:1848
eval @ vue.esm.js?a026:1865
Promise.catch (async)
invokeWithErrorHandling @ vue.esm.js?a026:1865
invoker @ vue.esm.js?a026:2188
original._wrapper @ vue.esm.js?a026:7565
