### ISSUE TITLE
Reset button icon is not showing in the peer selector

### ISSUE THREAD

**Issue by fboucquez** [nemfoundation/symbol-desktop-wallet#256]
One button icon is not showing in the peer selector
![image](https://user-images.githubusercontent.com/36499647/79630697-110eba00-8186-11ea-872d-2dbc65546899.png)

_Originally posted by @decentraliser in https://github.com/nemfoundation/symbol-desktop-wallet/pull/177#issuecomment-615643676_

This is in current master.

**Comment by decentraliser** [comment]
Nice
