### ISSUE TITLE
Assets Balance not showing custom mosaics

### ISSUE THREAD

**Issue by fboucquez** [nemfoundation/symbol-desktop-wallet#259]
I'm seeing that custom mosaic balances are not shown in the balance panel tab

http://api-01.ap-northeast-1.symboldev.network:3000/account/TDH3WI3AXBZJQMFI5XPTWRABTWVEDR54DMTHAB6I

![image](https://user-images.githubusercontent.com/5390558/79642274-f717ac00-8172-11ea-9468-62518f895831.png)

![image](https://user-images.githubusercontent.com/5390558/79642278-fe3eba00-8172-11ea-8465-20ef438e6043.png)

The owner of the mosaic doesn't have the balance either.

It should be fixed in my PR https://github.com/nemfoundation/symbol-desktop-wallet/pull/177

**Comment by fboucquez** [comment]
I think this is a loading/timing issue. If I go to mosaic and refresh the mosaic is back to assets. My PR should fix it

**Comment by decentraliser** [comment]
This would be a serious regression, are you sure that they are not hidden (from the second tab of the balance panel)?

**Comment by fboucquez** [comment]
https://drive.google.com/file/d/1M3FfLeFmUi8UvxkXWpw6EoUuFyoHB4sa/preview

I believe my PR will fix it. It prefetches owned and balance mosaics for all known addreses/wallets

**Comment by evias** [comment]
status update after merge of #177 @fboucquez ?

**Comment by evias** [comment]
fixed with 0.9.9
