### ISSUE TITLE
Should Owned Mosaic Table show Symbol mosaic?

### ISSUE THREAD

**Issue by fboucquez** [nemfoundation/symbol-desktop-wallet#260]
The logged user is not the owner of Symbol, but still, the wallet is showing Symbols and mosaics with balances owned by other accounts. 

![image](https://user-images.githubusercontent.com/5390558/79642445-dc920280-8173-11ea-8c27-a0fd32b31a77.png)

I think we should remove the non-owned mosaics. For balances, you have the dashboard.  If the wallet is showing not owned mosaic, I reckon we should change the title then.

This issue is related to https://github.com/nemfoundation/symbol-desktop-wallet/issues/259 , some mosaics may not be shown.

My PR only shows the custom mosaics the logged account created. 
https://github.com/nemfoundation/symbol-desktop-wallet/pull/177
I can change it if you want to be different.

**Comment by decentraliser** [comment]
opened a thread in Slack
https://nem2.slack.com/archives/CME5PV744/p1587251927025600

**Comment by fboucquez** [comment]
https://drive.google.com/file/d/1M3FfLeFmUi8UvxkXWpw6EoUuFyoHB4sa/preview

**Comment by evias** [comment]
as discussed during sprint call:

- The owned mosaics list should be renamed `Mosaics list`

**Comment by fboucquez** [comment]
After 177 pr, master branch shows owned mosaic (including when the balance is 0) and mosaics from other users (when the balance is > 0). I think just the title rename will do the trick

**Comment by decentraliser** [comment]
This is fixed in master already
