### ISSUE TITLE
Transaction Details Popup amount colors

### ISSUE THREAD

**Issue by fboucquez** [nemfoundation/symbol-desktop-wallet#261]
I'm seeing some coloring problems in the Transactions Details shown amounts: 

![image](https://user-images.githubusercontent.com/5390558/79642750-c2592400-8175-11ea-928f-096241785c55.png)

Should lost currencies be red? 

They are shown red in the transaction table

![image](https://user-images.githubusercontent.com/5390558/79642785-e7e62d80-8175-11ea-9b82-9eca7a0ed4f1.png)

What about zero values? Should they be gray/neutral?

![image](https://user-images.githubusercontent.com/5390558/79642836-2bd93280-8176-11ea-8de6-abdb1480bc55.png)

The same 0 value may be shown in red or green.

My PR fixed the Paid Fee red coloring but I want to confirm. I can fix the mosaic too.

**Comment by evias** [comment]
Yes red for **outgoing**.

**Comment by fboucquez** [comment]
What about 0 values? red/green/gray?
