### ISSUE TITLE
Desktop wallet product improvement2: Top account switch

### ISSUE THREAD

**Issue by NemTechCN** [nemfoundation/symbol-desktop-wallet#264]
**Top account switch， content of modification：**

- Displays more detailed account information and profile information more detailed
- Migrate the exit program here
- Migrate profile password changes here
- Add deletion of profile
- Add account deletion
- Add Mnemonic backup
- Import the seed account or private key account 

**Refer to the model**（please ignore other parts of product)

![1](https://user-images.githubusercontent.com/45383558/79740097-b3b76c00-8331-11ea-9f8c-a5f739ea2271.png)

**Comment by evias** [comment]
pending mockup review
