### ISSUE TITLE
Transfer Transaction Details not showing alias name

### ISSUE THREAD

**Issue by fboucquez** [nemfoundation/symbol-desktop-wallet#271]
![image](https://user-images.githubusercontent.com/5390558/79893576-a7d3b480-83da-11ea-880c-8e5f44991e4d.png)

**Comment by fboucquez** [comment]
It wil be fixed in https://github.com/nemfoundation/symbol-desktop-wallet/pull/177

**Comment by evias** [comment]
fixed with merge of #177
