### ISSUE TITLE
Use rest's network configuration to resolve the network currency

### ISSUE THREAD

**Issue by fboucquez** [nemfoundation/symbol-desktop-wallet#278]
At the moment, the wallet is revisiting the block/1 transactions to get information about the network currency.

https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/src/services/MosaicService.ts#L179

This is cumbersome and could have problems when there are 2 network currencies (like main and harvest).

Rest has a `currencyMosaicId` property here:

http://api-01.us-west-1.symboldev.network:3000/network/properties

The wallet can just load the mosaic info from that id. Note that the network properties are already loaded here https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/src/services/NetworkService.ts#L57
stored in the `NetworkModel`. The NetworkCurrency resolution should use the already loaded properties there.

**Comment by decentraliser** [comment]
fixed in #289
