### ISSUE TITLE
Wallet details: wallet names are not reactive

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/symbol-desktop-wallet#28]
Wallet names should change in wallet details and wallet tiles as soon as updated

**Comment by decentraliser** [comment]
The root cause is that the models use maps, and maps are not reactive

I don't see any clean fix here, appart from dropping the use of maps in favour of Record<key, value> in database entities, which will be a significant task

If you are OK with that, maybe we can open a separate issue @evias

**Comment by evias** [comment]
an alternative would be to make sure the WalletSelectorPanel list gets update **forcefully** as soon as the name was updated ("re-create()")

**Comment by evias** [comment]
fixed in v0.9.10
