### ISSUE TITLE
Transaction list: refresh button

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/symbol-desktop-wallet#284]
It seems that it disappeared again, but we must keep it

Before
![image](https://user-images.githubusercontent.com/36499647/80086335-21f76b00-858c-11ea-9aa7-3c58a5d53f68.png)

After
![image](https://user-images.githubusercontent.com/36499647/80086479-5bc87180-858c-11ea-8e17-b9617b8bc62a.png)

**Comment by vincent-lee90** [comment]
the switch is refresh, and the transaction list is reactive, so it is unnecessary to put the refresh button here

**Comment by decentraliser** [comment]
@evias you confirm it is not needed?

Le jeu. 23 avr. 2020 à 18:38, vincent-lee90 <notifications@github.com> a
écrit :

**Comment by evias** [comment]
@vincent-lee90 it happens that websocket connection drop when you have the wallet open for too long time.

I confirm the **need** for the refresh button.

**Comment by evias** [comment]
Please in the same PR, move the transaction filters to the **tab bar** ("Dashboard" / "Transfer" / "Invoice")

**Comment by vincent-lee90** [comment]
move the transaction filters, signer selector and refresh button up into the tab bar on dashboard
