### ISSUE TITLE
Import strategy: Add a back to login button

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/symbol-desktop-wallet#29]
Import strategy has no button to go back to login
Although it might make sense if there are no accounts in the database, it doesn't in the opposite situation

Once fixed, the back button in `inputAccountInfo` should redirect to import strategy

![image](https://user-images.githubusercontent.com/36499647/75839193-2c567d80-5e03-11ea-94e2-2c710e5cf6ac.png)

**Comment by NemTechCN** [comment]
![英文版-创建账户](https://user-images.githubusercontent.com/45383558/76501194-cad68480-647c-11ea-88fe-5e148cb9a560.png)
Interactive optimization and navigation to landing pages

**Comment by NemTechCN** [comment]
https://github.com/nemfoundation/symbol-desktop-wallet/pull/96  @evias @decentraliser
