### ISSUE TITLE
Enter a crafted URL in Settings -> Explorer URL cause the Desktop Wallet to freeze.

### ISSUE THREAD

**Issue by Flyy-yu** [nemfoundation/symbol-desktop-wallet#291]
Hey Guys, 

I come from your bug bounty program: https://hackerone.com/symbol.  I am not sure if my finding is in scope, I don't wanna risk my report get close as Informative or N/A and the finding doesn't really contain any sensitive information, so I decided to post here.

#### Why I think this is in scope: The finding falls into the low category:
Low
These would be mostly user experience level issues that render a end user to be stuck or applications to be useless. Typically this could be something like a user submitting to a form that breaks and user gets locked into a certain workflow until killing/quitting an application

#### Why I think this might not in scope. 
Out of scope features: Offline settings

Please let me know if this is a valid finding. 

### Summary
Enter a crafted URL in `Settings -> Explorer URL` cause the Desktop Wallet to freeze.

I believe this is caused by the regular expression used to validate the Explorer URL in `src/core/validation/validators/UrlValidator.ts`. The regular expression is so complex that it consumes lots of CPU when it runs against specific URLs.

```
  public static validate(value: any): boolean {
    const pattern = new RegExp('^(https?:\\/\\/)?' + // protocol
       '((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.?)+[a-z]{2,}|' + // domain name
       '((\\d{1,3}\\.){3}\\d{1,3}))' + // ip (v4) address
       '(\\:\\d+)?(\\/[-a-z\\d%_.~+]*)*' + // port
       '(\\#[-a-z\\d_]*)?$','i')
    return pattern.test(value)
  }
```

For more information about regex DOS: https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS

### Steps To Reproduce:
1. In the Setting interface, set the Explorer URL to "http://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.com/a?a=1"
2. Click Confirm

In the payload above, the question mark `?` is the character that causes the issue. I will expect to see a user accidentally enter or paste a question mark into the URL, so this is something that would likely happen. The situation gets worse if you try it in the Dev environment that runs the app in a browser.

### Supporting Material/References:

![Screen Shot 2020-04-25 at 6 50 50 PM](https://user-images.githubusercontent.com/25512004/80293117-86e8c780-872a-11ea-82b4-02e4d992bdae.png)

![Screen Shot 2020-04-25 at 6 51 01 PM](https://user-images.githubusercontent.com/25512004/80293118-89e3b800-872a-11ea-9733-2e0f7830cc89.png)

**Comment by vincent-lee90** [comment]
Thanks very much.
We'll fix it soon.

**Comment by Flyy-yu** [comment]
No Problem, please let me know if this is eligible for the reward(https://hackerone.com/symbol?view_policy=true). I will report back to HackerOne with this issue as a reference if this is eligible for the reward.

**Comment by vincent-lee90** [comment]
Sorry, It's not up to me.

**Comment by Flyy-yu** [comment]
@evias might be the person that knows the answer.

**Comment by evias** [comment]
Thanks for your report @Flyy-yu, I will come back to you during the day!

We are now evaluating the issue and will report whether this should be posted on Hackerone or is not eligible for our program.

Thank you for reporting!

**Comment by kaiyzen** [comment]
@Flyy-yu please go ahead and file an h1 report for this

**Comment by Flyy-yu** [comment]
Thanks, guys! 
Here is the report https://hackerone.com/reports/877413

**Comment by Flyy-yu** [comment]
@kaiyzen @evias Not sure if your guys noticed my response.

**Comment by Flyy-yu** [comment]
Hey @kaiyzen @evias, is there any update on processing the report?

**Comment by Flyy-yu** [comment]
@evias @kaiyzen The issue has been fixed and closed, is there any update for the report "https://hackerone.com/reports/877413" on HackerOne? Regardless about the bounty, if my report can be triaged and mark as solved that would be great. At least I can earn some reputation points on the platform. 

Thanks!
