### ISSUE TITLE
Invalid profile network banner hides the Peer Selector

### ISSUE THREAD

**Issue by fboucquez** [nemfoundation/symbol-desktop-wallet#302]
![image](https://user-images.githubusercontent.com/5390558/80441858-2a300d00-88e2-11ea-90dd-16b92d309352.png)

This is the testnet upgrade PR. If you select an incorrect peer, you may want to go back to the profile's network. Currently, select is being hidden behind the warning banner. 

If the warning banner is converted to a full-on modal dialog where just logout is the option I'll keep the selector so the user can come back to the original network.

**Comment by decentraliser** [comment]
meh....
I'm gonna give a fixed size to the wallet selector instead, because it should be fixed anyway...

**Comment by decentraliser** [comment]
before
![image](https://user-images.githubusercontent.com/36499647/80451406-5eddac00-8956-11ea-8d2f-c6c8f07c44f7.png)

after
![image](https://user-images.githubusercontent.com/36499647/80451610-da3f5d80-8956-11ea-8fc6-edd7b43eb97d.png)

**Comment by decentraliser** [comment]
Created an issue to go beyond this quickfix: #306

**Comment by decentraliser** [comment]
quickfixed by #294
