### ISSUE TITLE
Import wallet text update

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/symbol-desktop-wallet#312]
As far as I know we are only using 24 word seeds but the dialogue on the page says "12 or 24". 

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/10395907/80659671-38e80280-8a4f-11ea-9136-698128d228ae.png">

**Comment by decentraliser** [comment]
12 words seed work as well

for reference: https://github.com/nemfoundation/symbol-desktop-wallet/issues/43
