### ISSUE TITLE
Update electron build/config to not allow chance of remote execution

### ISSUE THREAD

**Issue by kaiyzen** [nemfoundation/symbol-desktop-wallet#324]
A h1 report was submitted, will add more details, filing this so we have placeholder and can attach issue number to report.

This is referenced page: https://www.electronjs.org/docs/tutorial/security#2-do-not-enable-nodejs-integration-for-remote-content

https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/public/build.js#L210

```
function createWindow() {
...code...
    const windowOptions = {
      minWidth: width,
      minHeight: height,
      width: width,
      height: height,
      title: app.getName(),
      titleBarStyle: 'hiddenInset',
      webPreferences: {
        nodeIntegration: true,
      },
      resizable: true,
    }
....code...
}
```

**Comment by decentraliser** [comment]
in index.js, webPreferences.nodeIntegration shall not be used

v-html is used to display articles in the news section, it should be dropped in favour of a WebView or equivalent

**Comment by decentraliser** [comment]
Please [check my proposal on Slack](https://nem2.slack.com/archives/CME5PV744/p1588843587107700)
