### ISSUE TITLE
Bug with partial transaction list sort direction

### ISSUE THREAD

**Issue by evias** [nemfoundation/symbol-desktop-wallet#325]
Partial transactions are listed in the wrong sorting direction. Currently the **latest** partial transaction will show up as the last partial in the list. It should be reversed.

Please make sure to also verify unconfirmed transaction sort direction.

Screenshot for illustation (look at the timing of partials):

<img width="921" alt="Screenshot 2020-05-04 at 4 06 54 PM" src="https://user-images.githubusercontent.com/141805/80974755-723eba80-8e21-11ea-91c9-39e28544df30.png">

**Comment by vincent-lee90** [comment]
I think the root of this problem is that the order of partialTransaction returned to us by SDK is different from that of confirmedTransaction
