### ISSUE TITLE
The network configuration name should be a variable

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/symbol-desktop-wallet#33]
This key should be made a variable, set when initializing the app

![image](https://user-images.githubusercontent.com/36499647/75839491-e3eb8f80-5e03-11ea-8acc-f61a61f84bc3.png)

**Comment by fboucquez** [comment]
The static config is used in different components when it should be loaded from rest or maybe the local db cache.

https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/src/components/MosaicAmountDisplay/MosaicAmountDisplayTs.ts#L26

**Comment by decentraliser** [comment]
yeah, this is what I'm referencing, we need a clean way to handle this, I think we should wait for the SDK to implement the network information endpoint

**Comment by fboucquez** [comment]
Yes, you are right. I think we can now improve how the UI component read the mosaic information (like for example a getter or service) and centralize the resolving in one place. Once we got the Rest/SDK improvement, the centralized place can be improved. 

In Java we have this repository factory [method](https://github.com/nemtech/symbol-sdk-java/blob/master/sdk-core/src/main/java/io/nem/symbol/sdk/api/RepositoryFactory.java#L139) now, something like this could help in the Wallet.
