### ISSUE TITLE
In a transfer transaction, if the recipient enters an alias, the recipient can't obtain transaction records after the transfer is completed.

### ISSUE THREAD

**Issue by Alicely** [nemfoundation/symbol-desktop-wallet#340]
Repeat steps：
1. Switch to the transfer page
2. The recipient enters an alias
3. After the transaction is successful, return to the recipient's dashboard to view the transaction list
4. You will not be able to see the record of this transaction

**Comment by decentraliser** [comment]
Hi @Alicely, Thanks for your contribution!
This is a known issue in REST side, you can follow its status here:
https://github.com/nemtech/catapult-rest/issues/223

**Comment by Alicely** [comment]
@decentraliser  OK，Thank you！
