### ISSUE TITLE
From the user's perspective, the Login button on the import wallet page is a bit strange.

### ISSUE THREAD

**Issue by Alicely** [nemfoundation/symbol-desktop-wallet#341]
Probably because it is not the last step of the entire import process, nor did it directly enter the dash
board.  maybe the “next” is more appropriate.
<img width="961" alt="图片1" src="https://user-images.githubusercontent.com/47626403/81472010-e31e1200-9227-11ea-8f2c-728f1761f89b.png">

**Comment by evias** [comment]
confirmed, `Next` is appropriate
