### ISSUE TITLE
Styles of modal look strange

### ISSUE THREAD

**Issue by vincent-lee90** [nemfoundation/symbol-desktop-wallet#348]
![image](https://user-images.githubusercontent.com/10797419/81634394-7f6f3100-9441-11ea-8bdc-c570511f36ec.png)
![image](https://user-images.githubusercontent.com/10797419/81634466-acbbdf00-9441-11ea-9b5e-b955a817f898.png)
![image](https://user-images.githubusercontent.com/10797419/81634548-c4936300-9441-11ea-842f-d8ab24c63cbd.png)
![image](https://user-images.githubusercontent.com/10797419/81634574-d248e880-9441-11ea-9c17-aae80b84da0a.png)
![image](https://user-images.githubusercontent.com/10797419/81634593-dd037d80-9441-11ea-801a-f5882707c034.png)

**Comment by vincent-lee90** [comment]
1.the title of modal should be `text-align:left`.
2.the text of modal title should not be truncated .
2.the width  of modal content  should have a fixed value or a min-width
3.scroll bar should be shown correctly
4.the four corners  of  modal should be shown correctly

**Comment by evias** [comment]
Please use this task to re-design the modal boxes so that they appear with a left side menu.

You should use `slots` in the Modal component to permit overwrite of the menu and the body (separately) in subcomponents.

**Comment by fullcircle23** [comment]
@vincent-lee90 @evias  I have a couple of other suggestions to improve the consistency in the layout and choice of buttons in the Modal boxes:

1. Modal boxes that **do not** need user input should **not** show `Cancel` and `OK` buttons as these buttons have the same effect which is close the modal window. Hence these 2 buttons should be replaced with a single `Close` button. 

_Examples of affected modals:_
- Console
- Transaction details
- .._more_


2. Modal boxes that **need** user input should:
- Show the buttons in modal-footer, not in modal-body.
- Have 2 buttons: `Cancel` and the submit form action (e.g. `Send`, `Submit`, `Sign`, `Confirm`, etc.)

_Examples of affected modals:_
- Link alias
- Unlink alias
- Modify supply
- .._more_
