### ISSUE TITLE
Multi-level co-signing transfer transaction is unsuccessful

### ISSUE THREAD

**Issue by Alicely** [nemfoundation/symbol-desktop-wallet#349]
**Scenario：2-level multisig account**

- 4-of-4 multisignature account  （multisig account：M    cosigners：A、B、C、D）
- 1-of-1 multisignature account  （multisig account：D     cosigner：E）   

**steps：**
1. A initiates a transfer transaction for M.
2. B and C both completed signing normally.
3. D can see the partial transactions of the M account, after entering the password to confirm, there is no feedback and the signing is not successful.
4. E can't view M's partial transaction, nor sign.
5. This transfer transaction was unsuccessful.

**Comment by decentraliser** [comment]
Nice catch!
This issue is on the SDK side
https://github.com/nemtech/symbol-sdk-typescript-javascript/issues/417
