### ISSUE TITLE
Invalid profile should  can be reset

### ISSUE THREAD

**Issue by David0817** [nemfoundation/symbol-desktop-wallet#353]
1. In the app, when the registration or import is larger than the first step, and then the app is closed, invalid profile will be saved
2. In the web, when the registration or import  is larger than the first step and the page is refreshed, invalid profile will be saved and the back button will not work

The above invalid profile should be allowed to be re-registered or imported

3. The login page should not display invalid profile in the list
4. When registering, step 3 _Backup Mnemonic Phrase_ should go straight back to step 1 _Create Profile_ and delete current profile

**Comment by evias** [comment]
I don't understand what it means for a registration to be `larger` ? Please elaborate.

Also, instead of deleting the profile, 4) should simply redirect the user where he left of.

**Comment by David0817** [comment]
@evias 
registration 5 steps
1. The Create Profile college  
2. Generate Mnemonic college  
3. Backup Mnemonic Phrase college  
4. Verify Mnemonic Phrase college  
5. Finish

Import 4 steps
1. The Create Profile  
2. The Mnemonic Passphrase college 
3. Select the Accounts college 
4 Finish

When the first step is completed  (the Profile has been stored) and go to  other steps , the invalid profile is left  when the unexpected exits.

When I enter next time, the last incomplete profile may be right, but  I don't want to complete or i want to chose import. there is no button to jump to base  guide page.my idea is that I can continue to register or import with the same profile, rather than jump to the last exit step. Because the frequency of registration is not that high.

**Comment by David0817** [comment]
<img width="1173" alt="WeChat56cc15d25ab49683b4b2d01c8e4e33f5" src="https://user-images.githubusercontent.com/18167466/82293446-21ad8c80-99df-11ea-9540-15c3e2a6a5a0.png">
<img width="1262" alt="WeChatd512bed8d02a4599f2b36de5f5f92e39" src="https://user-images.githubusercontent.com/18167466/82293463-27a36d80-99df-11ea-9bf0-eafaf1660524.png">

When I was in the third Backup Mnemonic, now I can only back to Generate Mnemonic college. I think it can skip the second step and go back to the first step to reset the profile.
