### ISSUE TITLE
Add recommended max fee to the selector.  

### ISSUE THREAD

**Issue by fboucquez** [nemfoundation/symbol-desktop-wallet#365]
Add new options to the max fee selector that calculates the max fee based on the transaction sizes, cosignatures needed, and a fee multipliers.

https://nemtech.github.io/concepts/fees.html#transaction-fee

To be defined which options are going to be shown to the user, the options can be defined in the configuration file

**Comment by vincent-lee90** [comment]
i think  #196 #241 is the same issue
