### ISSUE TITLE
vee-validate custom validation rules messages do not react to locale change

### ISSUE THREAD

**Issue by Alicely** [nemfoundation/symbol-desktop-wallet#374]
At present, all pages are like this, for example:

<img width="949" alt="图片1" src="https://user-images.githubusercontent.com/47626403/82400682-8540c400-9a8a-11ea-9c1b-13d444145d48.png">
<img width="949" alt="图片2" src="https://user-images.githubusercontent.com/47626403/82400726-9e497500-9a8a-11ea-91d8-cfa2f79ab679.png">
<img width="951" alt="图片3" src="https://user-images.githubusercontent.com/47626403/82400744-a6a1b000-9a8a-11ea-8661-2a07272eed93.png">
<img width="953" alt="图片4" src="https://user-images.githubusercontent.com/47626403/82400771-b4573580-9a8a-11ea-80c6-7fe696bcfdf2.png">

**Comment by evias** [comment]
what is the proposal with this issue ?

**Comment by Alicely** [comment]
When I switch languages, the verification message of the input box can be changed synchronously
