### ISSUE TITLE
When mosaic has no data, the drop-down style of mosaic is abnormal.

### ISSUE THREAD

**Issue by NemTechCN** [nemfoundation/symbol-desktop-wallet#388]
<img width="955" alt="图片11" src="https://user-images.githubusercontent.com/45383558/82788235-a5152500-9e9a-11ea-8c97-0023fbd6dd3b.png">

Normal should be like this：
<img width="950" alt="图片12" src="https://user-images.githubusercontent.com/45383558/82788429-0937e900-9e9b-11ea-9ad2-d4a42849d658.png">

**Comment by vincent-lee90** [comment]
Same to #347
