### ISSUE TITLE
Explorer link in Settings is the 941

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/symbol-desktop-wallet#401]
Needs to be updated to 951 http://explorer-951.symboldev.network/

**Comment by fullcircle23** [comment]
@jabo38 which release of the wallet are you using? The latest release i.e. 0.10.0 is showing 951 as per the `explorerUrl` setting in [network.conf.json](https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/config/network.conf.json)

**Comment by soonjing** [comment]
> @jabo38 which release of the wallet are you using? The latest release i.e. 0.10.0 is showing 951 as per the `explorerUrl` setting in [network.conf.json](https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/config/network.conf.json)

He probably meant that the "Details about a transaction" window transaction hash link is pointed to 941 network instead of 951. 

![image](https://user-images.githubusercontent.com/39853992/83748704-2d62a980-a695-11ea-8395-1d71d38e55dd.png)

**Comment by soonjing** [comment]
> Needs to be updated to 951 http://explorer-951.symboldev.network/

Go to "Settings" --> "General Settings" --> Change the "Explorer URL" to the latest explorer link.
This will solve the problem. 
![image](https://user-images.githubusercontent.com/39853992/83749644-97c81980-a696-11ea-86b9-9f77ee428a35.png)

**Comment by fullcircle23** [comment]
@jabo38 Actually this setting was missed in the wallet client database migration from 941 to 951. I'm working on the fix. Thanks for the feedback.
