### ISSUE TITLE
error message don't automatically disapear after entering the correct password

### ISSUE THREAD

**Issue by garm01** [nemfoundation/symbol-desktop-wallet#411]
The message "This password is incorrect" should disappear automatically when the correct password is entered.
![passw_is_incorrect](https://user-images.githubusercontent.com/46584115/84140881-93af4980-aa52-11ea-8d85-39357894a3bf.png)

**Comment by fullcircle23** [comment]
This happens on all boxes which require password to be entered.

**Comment by garm01** [comment]
If the password is entered correctly afterwards, the message should automatically disappear.
Otherwise the user does not know whether the entry was correct.
