### ISSUE TITLE
Failed to send multi sign

### ISSUE THREAD

**Issue by vincent-lee90** [nemfoundation/symbol-desktop-wallet#428]
![image](https://user-images.githubusercontent.com/10797419/85269507-8e1e1e80-b4aa-11ea-8f93-e3fae4d8ab69.png)

**Comment by vincent-lee90** [comment]
![image](https://user-images.githubusercontent.com/10797419/85269709-d9383180-b4aa-11ea-8825-2eadf40169cb.png)

**Comment by evias** [comment]
fixed with [v0.12.0](https://github.com/nemfoundation/symbol-desktop-wallet/releases/tag/v0.12.0)
