### ISSUE TITLE
When no information is entered for an invoice, just show the address in the QR

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/symbol-desktop-wallet#444]
Right now there is no QR being shown in this screen shot. 

If there is no information being shown, then just the QR code for the address should be shown, but once somebody starts to type information for an invoice, then the QR can update. 

![image](https://user-images.githubusercontent.com/10395907/86056720-7d7a2500-ba23-11ea-890b-0f09ad8d4254.png)

**Comment by vincent-lee90** [comment]
same to #409
