### ISSUE TITLE
Wallet version 0.11 does not work with new nodes 0.9.6.2.

### ISSUE THREAD

**Issue by DrCryptos** [nemfoundation/symbol-desktop-wallet#454]
Wallet version 0.11 does not work with new nodes 0.9.6.2.
Nodes 0.9.5.1 - everything works fine.
If you "embed" nodes in version 0.9.6.2 in the wallet, an error appears and the wallet stops working
PS 35.202.153.18

![Аннотация 2020-07-11 141527](https://user-images.githubusercontent.com/67805522/87222977-50ae0200-c381-11ea-9b07-d582e6fdcd97.jpg)
![Аннотация 2020-07-11 141658](https://user-images.githubusercontent.com/67805522/87222981-53a8f280-c381-11ea-8eeb-697f1ea18e25.jpg)

 - my node

**Comment by evias** [comment]
Hello,

We published v0.12.0 today which has compatibility for the Testnet you are trying to use! 

:warning: Mind that a database reset happens after you run the software for the first time because the testnet has been reset and accounts have become incompatible.

Thank you for your report!
