### ISSUE TITLE
Child account creation bugs

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/symbol-desktop-wallet#64]
All wallets in the database do not show in wallet selector

It should not be possible to create a wallet with the path: "m/44'/4343'/10'/0'/0'"
The wallet with the path "m/44'/4343'/10'/0'/0'" can be created and unlimited number of times

**Comment by evias** [comment]
The limit of 10 wallets does not make sense. Ultimately the derivation path is just another input that the end-user may want to manage. (Not in current state.)

If wallet selector is limited to showing 10 wallets, it should be fixed

**Comment by decentraliser** [comment]
The limit of 10 wallets is a requirement that was decided during weekly meetings. if we stick to that, only the paths 0 to 9 should be available, not 10

ill fix that tomorrow
