### ISSUE TITLE
Mosaic table: set back show / hide expired mosaic button

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/symbol-desktop-wallet#66]

**Comment by decentraliser** [comment]
please set back the refresh button also

**Comment by NemTechCN** [comment]
<img width="953" alt="show " src="https://user-images.githubusercontent.com/45383558/76501028-85b25280-647c-11ea-86aa-f5b0330ddcc5.png">
shall do it like this

**Comment by decentraliser** [comment]
hi! not sure about this refresh icon but yes, that's the idea

**Comment by evias** [comment]
fixed with 28e1ac6c
