### ISSUE TITLE
Transaction details popover

### ISSUE THREAD

**Issue by NemTechCN** [nemfoundation/symbol-desktop-wallet#86]
**Requirements Description**

1. Popover form style of transaction details (as shown in the figure)
(1) Form status bar: light purple, enhanced close button display,
(2) Delete the extra "cancel /ok" button at the bottom
2. Transaction information content adjustment
(1)  modification items:
-  "transaction details" title changed to "Inner Transactions", through the drop-down box compatible with multiple internal transactions display.
- Paid Fee) shall be changed to a relative value to avoid misunderstandings 
-  Deadline time, remove “ms” display
3. Correction of size, color and alignment of contents（reference to picture)
4. I18n internationalization

View now
![image](https://user-images.githubusercontent.com/45383558/76593250-c4a1e000-6530-11ea-9813-e670fab675cf.png)

Target view
![image](https://user-images.githubusercontent.com/45383558/76593278-d84d4680-6530-11ea-8a1e-ff4a222519cb.png)

**Comment by fboucquez** [comment]
Note the high Paid Fee. It's using the relative amount, we should move the decimal comma Divisibility (6) places to the left.

**Comment by decentraliser** [comment]
The max fee and paid fee absolute amount displayed as relative is fixed in #191
