### ISSUE TITLE
Mnemonic phrase - word repeated so check couldn't be passed, error "Mnemonic isn't correct"

### ISSUE THREAD

**Issue by Kyrylog** [nemfoundation/symbol-desktop-wallet#87]
![image](https://user-images.githubusercontent.com/33864106/76616533-daada180-652c-11ea-9b82-f4fd0d4f8b5e.png)
![image](https://user-images.githubusercontent.com/33864106/76616745-5e678e00-652d-11ea-8a36-8ff32950f8e9.png)

**Comment by Kyrylog** [comment]
![image](https://user-images.githubusercontent.com/33864106/76621714-b5269500-6538-11ea-86a3-dc6a01d18c81.png)

**Comment by decentraliser** [comment]
@evias, do you want to fix it on hd wallet side, or wallet side?

**Comment by decentraliser** [comment]
Thanks for reporting @Kyrylog !
