### ISSUE TITLE
"Sizing" issue

### ISSUE THREAD

**Issue by OlegMakarenko** [nemfoundation/symbol-desktop-wallet#89]
Transactions pagination and navigation menu goes off  screen when window `width` > `2.2 * height`

![1](https://user-images.githubusercontent.com/33131259/76637887-317aa180-6554-11ea-82c5-92a1e9b4b8ca.JPG)

**Comment by David0817** [comment]
pagination was fixed in #111

**Comment by NemTechCN** [comment]
about "navigation menu goes off screen " , that build need the stable heigh and width in electron , which win had done , mac not do.
